---
- name: Refresh GoDaddy certs and rebuild PFX locally
  hosts: localhost
  gather_facts: true
  vars_files:
    - "./secrets.yml"
  vars:
    pfx_dir: "./certs"
    renew_days: 60
    force_rebuild_chain: false
    work_dir: "./gd_pfx_work"

  tasks:
    - name: Init rotation summary
      set_fact:
        rotated_certs: []

    - name: Ensure work dir
      file:
        path: "{{ work_dir }}"
        state: directory
        mode: "0700"

    - name: Find local PFX files
      find:
        paths: "{{ pfx_dir }}"
        patterns: "*.pfx"
        file_type: file
      register: pfx_files

    - name: Fail if no pfx found
      fail:
        msg: "No .pfx files found in {{ pfx_dir }}"
      when: pfx_files.matched | int == 0

    - name: Process each PFX
      include_tasks: pfx_rotate_item.yml
      loop: "{{ pfx_files.files }}"
      loop_control:
        label: "{{ item.path }}"
      vars:
        pfx_path: "{{ item.path }}"

    - name: Rotation summary
      debug:
        msg: >-
          {{
            (
              ['Rotated certs: ' ~ (rotated_certs | length | string)]
              + (rotated_certs | default([]))
            ) | join('\n')
          }}
